Repository RandomUserIK/HomesFromArchitectsWebPage-frontend, pull requests merged in 2021-04, with the labels that each got.

#11 Hfa 56
  src/app/admin-view/admin-view.module.ts
  src/app/admin-view/components/admin-projects-gallery/admin-projects-gallery.component.html
  src/app/admin-view/components/admin-projects-gallery/admin-projects-gallery.component.ts
  src/app/admin-view/components/create-project/create-project.component.html
  src/app/admin-view/components/create-project/create-project.component.scss
  src/app/admin-view/components/create-project/create-project.component.spec.ts
  src/app/admin-view/components/create-project/create-project.component.ts
  src/app/admin-view/components/create-project/create-project.module.ts
  src/app/admin-view/components/create-project/resources/common-project-data-fields.ts
  src/app/admin-view/components/create-project/resources/project-data-fields-injectable.ts
  src/app/admin-view/components/create-project/services/create-common-project.service.ts
  src/app/admin-view/components/create-project/services/create-project.service.spec.ts
  src/app/admin-view/services/file-service.ts
  src/app/app.module.ts
  src/app/auth/auth.component.ts
  src/app/components/data-fields/components/data-field-resolver/data-field-resolver.component.html
  src/app/components/data-fields/components/data-field-resolver/data-field-resolver.component.spec.ts
  src/app/components/data-fields/components/data-field-resolver/data-field-resolver.component.ts
  src/app/components/data-fields/components/dynamic-gallery-field/dynamic-gallery-field.component.html
  src/app/components/data-fields/components/dynamic-gallery-field/dynamic-gallery-field.component.scss
  src/app/components/data-fields/components/dynamic-gallery-field/dynamic-gallery-field.component.spec.ts
  src/app/components/data-fields/components/dynamic-gallery-field/dynamic-gallery-field.component.ts
  src/app/components/data-fields/components/dynamic-text-section-field/dynamic-text-section-field.component.html
  src/app/components/data-fields/components/dynamic-text-section-field/dynamic-text-section-field.component.scss
  src/app/components/data-fields/components/dynamic-text-section-field/dynamic-text-section-field.component.spec.ts
  src/app/components/data-fields/components/dynamic-text-section-field/dynamic-text-section-field.component.ts
  src/app/components/data-fields/components/enumeration-field/enumeration-field.component.html
  src/app/components/data-fields/components/enumeration-field/enumeration-field.component.scss
  src/app/components/data-fields/components/enumeration-field/enumeration-field.component.spec.ts
  src/app/components/data-fields/components/enumeration-field/enumeration-field.component.ts
  src/app/components/data-fields/components/file-field/file-field.component.html
  src/app/components/data-fields/components/file-field/file-field.component.spec.ts
  src/app/components/data-fields/components/file-field/file-field.component.ts
  src/app/components/data-fields/components/multichoice-field/multichoice-field.component.html
  src/app/components/data-fields/components/multichoice-field/multichoice-field.component.spec.ts
  src/app/components/data-fields/components/multichoice-field/multichoice-field.component.ts
  src/app/components/data-fields/components/primitive-type-field/primitive-type-field.component.html
  src/app/components/data-fields/components/primitive-type-field/primitive-type-field.component.scss
  src/app/components/data-fields/components/primitive-type-field/primitive-type-field.component.spec.ts
  src/app/components/data-fields/components/primitive-type-field/primitive-type-field.component.ts
  src/app/components/data-fields/data-fields.module.ts
  src/app/components/data-fields/models/data-field-type.enum.ts
  src/app/components/data-fields/models/data-field.ts
  src/app/components/data-fields/models/data-group-map.ts
  src/app/components/data-fields/models/image-type.enum.ts
  src/app/components/data-fields/services/file-upload-validation.service.spec.ts
  src/app/components/data-fields/services/file-upload-validation.service.ts
  src/app/components/form-alert/form-alert.component.html
  src/app/components/form-alert/form-alert.component.spec.ts
  src/app/components/form-alert/form-alert.component.ts
  src/app/components/form-alert/form-alert.module.ts
  src/app/configuration/resources/config.json
  src/app/models/abstract-project-gallery.ts
  src/app/models/project-data.ts
  src/app/public-view/components/home/components/home-instagram-gallery/home-instagram-gallery.component.scss
  src/app/services/projects-service.ts
  src/index.html
Labels: enhancement

#15 HFA-62 - Umožniť nahrávanie viacerých fotiek pre pôdor
  src/app/admin-view/components/create-project/resources/common-project-data-fields.ts
  src/app/components/data-fields/models/image-type.enum.ts
Labels: refactor

#13 Hfa 66
  package-lock.json
  package.json
  src/app/components/data-fields/components/dynamic-gallery-field/dynamic-gallery-field.component.ts
  src/app/components/data-fields/components/file-field/file-field.component.ts
  src/app/components/data-fields/data-fields.module.ts
  src/app/components/data-fields/models/compressed-file.ts
  src/app/components/data-fields/services/file-upload-validation.service.ts
  src/app/components/data-fields/services/image-compression.service.ts
Labels: enhancement

#14 Hfa 60
  src/app/admin-view/components/create-project/create-project.component.html
  src/app/admin-view/components/create-project/create-project.component.ts
  src/app/admin-view/components/create-project/resources/common-project-data-fields.ts
  src/app/admin-view/services/file-service.ts
  src/app/app.module.ts
  src/app/components/data-fields/components/data-field-resolver/data-field-resolver.component.ts
  src/app/components/data-fields/components/data-fields-group/data-fields-group.component.html
  src/app/components/data-fields/components/data-fields-group/data-fields-group.component.spec.ts
  src/app/components/data-fields/components/data-fields-group/data-fields-group.component.ts
  src/app/components/data-fields/components/dynamic-gallery-field/dynamic-gallery-field.component.html
  src/app/components/data-fields/components/dynamic-gallery-field/dynamic-gallery-field.component.ts
  src/app/components/data-fields/components/dynamic-text-section-field/dynamic-text-section-field.component.ts
  src/app/components/data-fields/components/enumeration-field/enumeration-field.component.html
  src/app/components/data-fields/components/enumeration-field/enumeration-field.component.ts
  src/app/components/data-fields/components/file-field/file-field.component.html
  src/app/components/data-fields/components/file-field/file-field.component.ts
  src/app/components/data-fields/components/multichoice-field/multichoice-field.component.html
  src/app/components/data-fields/components/multichoice-field/multichoice-field.component.ts
  src/app/components/data-fields/components/primitive-type-field/primitive-type-field.component.html
  src/app/components/data-fields/components/primitive-type-field/primitive-type-field.component.ts
  src/app/components/data-fields/data-fields.module.ts
  src/app/configuration/resources/config.json
  src/app/configuration/resources/recaptcha-key-injectable.ts
  src/app/models/abstract-project-gallery.ts
  src/app/public-view/components/contacts/contact-form/contact-form.component.html
  src/app/public-view/components/contacts/contact-form/contact-form.component.ts
  src/app/public-view/components/contacts/contacts.component.scss
  src/app/public-view/components/contacts/contacts.component.ts
  src/app/public-view/components/contacts/services/contacts.service.ts
  src/app/public-view/components/home/components/home-icons-description/home-icons-description.component.scss
  src/app/public-view/components/order/components/order-form/models/order-form.ts
  src/app/public-view/components/order/components/order-form/order-form.component.html
  src/app/public-view/components/order/components/order-form/order-form.component.spec.ts
  src/app/public-view/components/order/components/order-form/order-form.component.ts
  src/app/public-view/components/order/components/order-form/resources/order-data-fields-injectable.ts
  src/app/public-view/components/order/components/order-form/services/order-form.service.spec.ts
  src/app/public-view/components/order/components/order-form/services/order-form.service.ts
  src/app/public-view/components/order/components/order-header/order-header.component.html
  src/app/public-view/components/order/components/order-header/order-header.component.spec.ts
  src/app/public-view/components/order/components/order-header/order-header.component.ts
  src/app/public-view/components/order/order.component.html
  src/app/public-view/components/order/order.component.spec.ts
  src/app/public-view/components/order/order.component.ts
  src/app/public-view/components/order/order.module.ts
  src/app/public-view/public-view.module.ts
  src/app/services/projects-service.ts
  src/theme.scss
Labels: enhancement

#16 Hfa 70 Refactor konktaktného formuláru pomocou dynamického form builderu
  package-lock.json
  src/app/components/data-fields/components/data-field-resolver/data-field-resolver.component.html
  src/app/components/data-fields/components/dynamic-gallery-field/dynamic-gallery-field.component.html
  src/app/components/data-fields/components/enumeration-field/enumeration-field.component.html
  src/app/components/data-fields/components/file-field/file-field.component.html
  src/app/components/data-fields/components/multichoice-field/multichoice-field.component.html
  src/app/components/data-fields/components/primitive-type-field/primitive-type-field.component.html
  src/app/components/data-fields/components/recaptcha-field/recaptcha-field.component.html
  src/app/components/data-fields/components/recaptcha-field/recaptcha-field.component.scss
  src/app/components/data-fields/components/recaptcha-field/recaptcha-field.component.spec.ts
  src/app/components/data-fields/components/recaptcha-field/recaptcha-field.component.ts
  src/app/components/data-fields/components/submit-button-field/submit-button-field.component.html
  src/app/components/data-fields/components/submit-button-field/submit-button-field.component.spec.ts
  src/app/components/data-fields/components/submit-button-field/submit-button-field.component.ts
  src/app/components/data-fields/components/text-area-field/text-area-field.component.html
  src/app/components/data-fields/components/text-area-field/text-area-field.component.scss
  src/app/components/data-fields/components/text-area-field/text-area-field.component.spec.ts
  src/app/components/data-fields/components/text-area-field/text-area-field.component.ts
  src/app/components/data-fields/data-fields.module.ts
  src/app/components/data-fields/models/data-field-type.enum.ts
  src/app/components/data-fields/models/data-field.ts
  src/app/configuration/resources/config.json
  src/app/public-view/components/contact-form-wrapper/contact-form-wrapper.component.html
  src/app/public-view/components/contact-form-wrapper/contact-form-wrapper.component.spec.ts
  src/app/public-view/components/contact-form-wrapper/contact-form-wrapper.component.ts
  src/app/public-view/components/contact-form-wrapper/contact-form-wrapper.module.ts
  src/app/public-view/components/contact-form-wrapper/contact-form/contact-form.component.html
  src/app/public-view/components/contact-form-wrapper/contact-form/contact-form.component.scss
  src/app/public-view/components/contact-form-wrapper/contact-form/contact-form.component.spec.ts
  src/app/public-view/components/contact-form-wrapper/contact-form/contact-form.component.ts
  src/app/public-view/components/contact-form-wrapper/contact-form/models/contact-form.ts
  src/app/public-view/components/contact-form-wrapper/contact-form/resources/contact-data-fields-injectable.ts
  src/app/public-view/components/contact-form-wrapper/services/contacts.service.spec.ts
  src/app/public-view/components/contact-form-wrapper/services/contacts.service.ts
  src/app/public-view/components/contacts/contact-form/contact-form.component.html
  src/app/public-view/components/contacts/contact-form/contact-form.component.ts
  src/app/public-view/components/contacts/contacts.component.ts
  src/app/public-view/components/projects-gallery/projects-gallery.module.ts
  src/app/public-view/public-view.module.ts
Labels: refactor

#17 Hfa 66 fix
  src/app/admin-view/services/file-service.ts
  src/app/auth/services/auth.service.ts
  src/app/components/data-fields/services/image-compression.service.ts
  src/app/models/project-data.ts
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.html
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.ts
  src/app/services/projects-service.ts
Labels: bug fix
