Repository RandomUserIK/HomesFromArchitectsWebPage-frontend, pull requests merged in 2021-05, with the labels that each got.

#18 Hfa 76 Zmena fontu
  src/app/public-view/components/header/header.component.scss
  src/assets/fonts/OpenSans.ttf
  src/assets/fonts/alegreya.ttf
  src/styles.scss
Labels: refactor

#20 Hfa-79 Odosielanie objednávkového formulára na email
  src/app/components/data-fields/components/multichoice-field/multichoice-field.component.ts
  src/app/configuration/resources/config.json
  src/app/public-view/components/contact-form-wrapper/contact-form/contact-form.component.ts
  src/app/public-view/components/contact-form-wrapper/contact-form/resources/contact-data-fields-injectable.ts
  src/app/public-view/components/order/components/order-form/order-form.component.html
  src/app/public-view/components/order/components/order-form/order-form.component.ts
  src/app/public-view/components/order/components/order-form/resources/order-data-fields-injectable.ts
  src/app/public-view/components/order/order.component.html
  src/app/public-view/components/order/order.component.ts
Labels: enhancement

#22 Hfa 71
  src/app/admin-view/components/create-project/resources/individual-project-data.ts
  src/app/admin-view/components/create-project/resources/project-data-fields-injectable.ts
Labels: enhancement

#23 feat(Gallery): Add loading for gallery photos in public view. Fix image …
  src/app/admin-view/services/file-service.ts
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.html
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.scss
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.ts
  src/app/services/projects-service.ts
Labels: bug fix, enhancement

#21 Hfa 72
  src/app/admin-view/components/create-project/create-project.component.html
  src/app/admin-view/components/create-project/create-project.component.ts
  src/app/admin-view/components/create-project/resources/interior-project-data.ts
  src/app/admin-view/components/create-project/resources/project-data-fields-injectable.ts
  src/app/app.component.html
Labels: enhancement

#31 HFA-89: Fix remaining image in image field
  src/app/components/data-fields/components/image-field/image-field.component.html
  src/app/components/data-fields/components/image-field/image-field.component.ts
Labels: bug fix

#30 HFA-96: Fix paging
  src/app/models/abstract-project-gallery.ts
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.scss
  src/app/public-view/components/projects-gallery/projects-gallery.component.html
Labels: bug fix

#29 HFA-93: Add title and usable area to gallery project
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.html
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.scss
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.ts
Labels: enhancement

#27 Hfa 32 - Separate application.properties and application.dev.properties
  src/app/admin-view/admin-view.module.ts
  src/app/admin-view/services/file-service.ts
  src/app/auth/services/auth.service.ts
  src/app/configuration/models/application-properties.ts
  src/app/configuration/resources/config.json
  src/app/configuration/services/application-configuration-service.ts
  src/app/configuration/services/configuration-service.ts
  src/app/public-view/components/contact-form-wrapper/services/contacts.service.ts
  src/app/public-view/components/order/components/order-form/services/order-form.service.ts
  src/app/services/projects-service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#28 HFA-85
  src/app/admin-view/components/create-project/services/create-project.service.ts
  src/app/admin-view/services/file-service.ts
  src/app/auth/auth.module.ts
  src/app/auth/models/auth-response.ts
  src/app/auth/services/auth-interceptor.service.ts
  src/app/auth/services/auth.service.ts
  src/app/models/abstract-project-gallery.ts
  src/app/models/pageable-projects-data.ts
  src/app/models/project-data.ts
  src/app/models/user/user-storage-data.ts
  src/app/models/user/user.ts
  src/app/models/web/request-bodies/auth-request.ts
  src/app/models/web/response-bodies/auth/authentication-message-resource.ts
  src/app/models/web/response-bodies/form/submitted-form-message-resource.ts
  src/app/models/web/response-bodies/image/image-upload-message-resource.ts
  src/app/models/web/response-bodies/project/pageable-project-message-resource.ts
  src/app/models/web/response-bodies/project/project-message-resource.ts
  src/app/public-view/components/project/components/general/project-view/abstract-project-view.ts
  src/app/services/projects-service.ts
Labels: enhancement, refactor

#34 Hfa 97 Aktualizácia projektu v admin sekcii
  src/app/admin-view/components/admin-projects-gallery/admin-projects-gallery.component.html
  src/app/admin-view/components/admin-projects-gallery/admin-projects-gallery.component.ts
  src/app/admin-view/components/admin-projects-gallery/components/admin-project-gallery/admin-project-gallery.component.ts
  src/app/admin-view/components/create-project/create-project.component.html
  src/app/admin-view/components/create-project/create-project.component.ts
  src/app/admin-view/components/create-project/resources/individual-project-data.ts
  src/app/admin-view/components/create-project/resources/interior-project-data.ts
  src/app/admin-view/components/create-project/services/create-project-form-initializer.service.ts
  src/app/admin-view/components/create-project/services/create-project.service.ts
  src/app/components/data-fields/components/multichoice-field/multichoice-field.component.ts
  src/app/models/abstract-project-gallery.ts
Labels: enhancement

#32 HFA-92
  src/app/models/project/individual-interior-project-title-text-data.ts
  src/app/public-view/components/project/components/individual-interior-project/individual-interior-project-title-text/individual-interior-project-title-text.component.html
  src/app/public-view/components/project/components/individual-interior-project/individual-interior-project-title-text/individual-interior-project-title-text.component.scss
  src/app/public-view/components/project/components/individual-interior-project/individual-interior-project-title-text/individual-interior-project-title-text.component.spec.ts
  src/app/public-view/components/project/components/individual-interior-project/individual-interior-project-title-text/individual-interior-project-title-text.component.ts
  src/app/public-view/components/project/components/individual-interior-project/individual-interior-project.component.html
  src/app/public-view/components/project/components/individual-interior-project/individual-interior-project.module.ts
  src/app/public-view/components/projects-gallery/projects-gallery.component.html
  src/app/public-view/components/projects-gallery/projects-gallery.component.ts
  src/app/public-view/components/projects-gallery/projects-gallery.module.ts
Labels: enhancement

#33 HFA-69
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.html
  src/app/public-view/components/projects-gallery/components/project-gallery/project-gallery.component.ts
Labels: enhancement

#36 HFA-91 - Instagram galéria ma nerovnomerné obrázky a chýba jej fotka
  src/app/public-view/components/home/components/home-instagram-gallery/home-instagram-gallery.component.html
  src/app/public-view/components/home/components/home-instagram-gallery/home-instagram-gallery.component.scss
  src/app/public-view/components/home/components/home-instagram-gallery/home-instagram-gallery.component.ts
Labels: bug fix

#25 Hfa 63
  angular.json
  src/app/models/pageable-projects-data.ts
  src/app/public-view/components/content/components/content-individual-project-photos/content-individual-project-photos.component.html
  src/app/public-view/components/content/components/content-individual-project-photos/content-individual-project-photos.component.spec.ts
  src/app/public-view/components/content/components/content-individual-project-photos/content-individual-project-photos.component.ts
  src/app/public-view/components/content/components/content-text-section/content-text-section.component.html
  src/app/public-view/components/content/components/content-text-section/content-text-section.component.scss
  src/app/public-view/components/content/components/content-text-section/content-text-section.component.spec.ts
  src/app/public-view/components/content/components/content-text-section/content-text-section.component.ts
  src/app/public-view/components/content/components/extended-content-header/extended-content-header.component.html
  src/app/public-view/components/content/components/extended-content-header/extended-content-header.component.scss
  src/app/public-view/components/content/components/extended-content-header/extended-content-header.component.spec.ts
  src/app/public-view/components/content/components/extended-content-header/extended-content-header.component.ts
  src/app/public-view/components/content/components/extended-content/extended-content.component.html
  src/app/public-view/components/content/components/extended-content/extended-content.component.scss
  src/app/public-view/components/content/components/extended-content/extended-content.component.spec.ts
  src/app/public-view/components/content/components/extended-content/extended-content.component.ts
  src/app/public-view/components/content/components/table/project-content-table.component.html
  src/app/public-view/components/content/components/table/project-content-table.component.scss
  src/app/public-view/components/content/components/table/project-content-table.component.spec.ts
  src/app/public-view/components/content/components/table/project-content-table.component.ts
  src/app/public-view/components/content/project-content.component.html
  src/app/public-view/components/content/project-content.component.scss
  src/app/public-view/components/content/project-content.component.spec.ts
  src/app/public-view/components/content/project-content.component.ts
  src/app/public-view/components/content/project-content.module.ts
  src/app/public-view/components/content/resources/content-data.ts
  src/app/public-view/components/content/resources/content-text-fields-injectable.ts
  src/app/public-view/components/content/resources/extended-content-data.json
  src/app/public-view/components/content/resources/table-content-data.json
  src/app/public-view/components/header/header.component.html
  src/app/public-view/components/projects-gallery/projects-gallery.component.ts
  src/app/public-view/public-view.module.ts
  src/app/services/projects-service.ts
  src/assets/fonts/FuturaLT-Book.woff
  src/fonts.scss
Labels: enhancement

#35 HFA-50 - Spracovanie osobnych udajov podstranka
  src/app/public-view/components/footer/footer.component.html
  src/app/public-view/components/gdpr/components/gdpr-text-section/gdpr-text-section.component.html
  src/app/public-view/components/gdpr/components/gdpr-text-section/gdpr-text-section.component.scss
  src/app/public-view/components/gdpr/components/gdpr-text-section/gdpr-text-section.component.spec.ts
  src/app/public-view/components/gdpr/components/gdpr-text-section/gdpr-text-section.component.ts
  src/app/public-view/components/gdpr/components/models/GdprTextSection.ts
  src/app/public-view/components/gdpr/components/models/gdpr-data.json
  src/app/public-view/components/gdpr/components/models/gdpr-data.ts
  src/app/public-view/components/gdpr/gdpr/gdpr.component.html
  src/app/public-view/components/gdpr/gdpr/gdpr.component.spec.ts
  src/app/public-view/components/gdpr/gdpr/gdpr.component.ts
  src/app/public-view/components/gdpr/gdpr/gdpr.module.ts
  src/app/public-view/public-view.module.ts
Labels: enhancement

#37 HFA-67 Endpoint pre instagram feed
  src/app/public-view/components/gdpr/components/models/GdprTextSection.ts
  src/app/public-view/components/home/components/home-instagram-gallery/home-instagram-gallery.component.ts
  src/app/public-view/components/home/models/instagram-post.ts
  src/app/public-view/components/home/services/Instagram-search-injectables.ts
  src/app/public-view/components/home/services/instagram-search.service.ts
  src/environments/environment.ts
Labels: enhancement

#39 HFA-88
  src/app/admin-view/services/file-service.ts
  src/app/components/image-carousel/image-carousel.component.html
  src/app/components/image-carousel/image-carousel.component.ts
  src/app/components/lightbox/lightbox.component.html
  src/app/components/lightbox/lightbox.component.ts
  src/app/components/lightbox/lightbox.module.ts
  src/app/components/lightbox/services/lightbox.service.spec.ts
  src/app/components/lightbox/services/lightbox.service.ts
Labels: refactor

#38 fix(Contact form): Fix contact form request
  src/app/admin-view/components/create-project/create-project.module.ts
  src/app/admin-view/components/create-project/services/create-project.service.ts
  src/app/models/web/request-bodies/image-file.ts
  src/app/public-view/components/order/components/order-form/order-form.component.ts
  src/app/public-view/components/order/components/order-form/services/order-form.service.ts
  src/app/public-view/components/order/order.component.html
  src/app/public-view/components/order/order.component.ts
  src/app/public-view/components/project/components/common-project/common-project-changes/common-project-changes.component.html
  src/app/public-view/components/project/components/common-project/common-project-changes/common-project-changes.component.scss
  src/app/public-view/components/project/components/common-project/common-project-price-comparison/common-project-price-comparison.component.html
  src/app/public-view/components/project/components/common-project/common-project-price-comparison/common-project-price-comparison.component.scss
  src/app/public-view/components/project/components/common-project/common-project.module.ts
  src/app/public-view/components/project/components/general/project.component.scss
  src/app/public-view/public-view.module.ts
  src/app/services/projects-service.ts
  src/app/services/request-entity-preparation.service.spec.ts
  src/app/services/request-entity-preparation.service.ts
Labels: bug fix

#41 HFA-86 - Nastaviť max input length na fronte a backende pre jednotlivé text input fieldy
  src/app/admin-view/components/admin-blog/resources/blog-article-data-fields-injectable.ts
  src/app/admin-view/components/create-project/resources/common-project-data-fields.ts
  src/app/admin-view/components/create-project/resources/individual-project-data.ts
  src/app/admin-view/components/create-project/resources/interior-project-data.ts
  src/app/components/data-fields/components/dynamic-text-section-field/dynamic-text-section-field.component.html
  src/app/components/data-fields/components/dynamic-text-section-field/dynamic-text-section-field.component.ts
  src/app/components/data-fields/components/primitive-type-field/primitive-type-field.component.html
  src/app/public-view/components/contact-form-wrapper/contact-form/resources/contact-data-fields-injectable.ts
  src/app/public-view/components/order/components/order-form/resources/order-data-fields-injectable.ts
Labels: enhancement
